services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leads-register-api
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
